version: '3.8'

services:
  web:
    container_name: ${DOCKER_CONTAINER_NAME}_web
    build:
      context: .
      args:
        XDEBUG_MODE: ${XDEBUG_MODE}
        XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST}
        XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
        XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT}
        XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL}
    ports:
      - ${DOCKER_PORT_WEB}
      - ${DOCKER_PORT_SSL}
    volumes:
      - .:/var/www/html
      - ./Docker/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./Docker/apache2/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf:ro
      - ./storage/logs:/var/www/html/storage/logs
      - ./storage/database:/var/www/html/storage/database
      
      - ./Docker/apache2/ssl:/etc/apache2/ssl:ro
      - ./storage/logs/apache2:/var/log/apache2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - XDEBUG_MODE=${XDEBUG_MODE}
      - XDEBUG_START_WITH_REQUEST=${XDEBUG_START_WITH_REQUEST}
      - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
      - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT}
      - XDEBUG_LOG_LEVEL=${XDEBUG_LOG_LEVEL}

volumes:
  db_data:
